services:
  db:
    image: postgres:17
    environment:  
      POSTGRES_DB: DotDev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cQlDkMk
    ports: 
      - "6432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: